spring.application.name=debtors_register
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
#jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=${APP_USER:-debtors_schema}
spring.datasource.password=${APP_USER_PASSWORD:-secret}